### ISSUE TITLE
Target of Detect

### ISSUE THREAD

**Issue by je5349** [Asadullah-Dal17/Yolov4-Detector-and-Distance-Estimator#3]
Hello.
I saw that you detected the face and estimated distances.
What I want is to detect a car and estimate the distance to it, is this possible with this code?

I saw that Car is among the recognition objects in "classes.txt" in your repository.
So, I think it is possible what i want.

If it's impossible, do i need to retrain the yolo-v4 or change something?

I look forward to your reply.
Thank you!

**Comment by Asadullah-Dal17** [comment]
Yeah, It's possible, you need a reference image, for that, 
You don't need to retrain for cars, it is already available in pre-trained yolov4 https://github.com/Asadullah-Dal17/Yolov4-Detector-and-Distance-Estimator/blob/master/classes.txt#L3
