### ISSUE TITLE
Error in running

### ISSUE THREAD

**Issue by HUNAR214** [Asadullah-Dal17/Yolov4-Detector-and-Distance-Estimator#7]
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-u4kjpz2z\opencv\modules\dnn\src\dnn.cpp (1451) cv::dnn::dnn4_v20210608::Net::Impl::setUpNet DNN module was not built with CUDA backend; switching to CPU
Traceback (most recent call last):
  File "c:/Users/hunar/Desktop/assignments/projects/object detection/Yolov4-Detector-and-Distance-Estimator/DistanceEstimation.py", line 73, in <module>
    mobile_width_in_rf = mobile_data[1][1]
IndexError: list index out of range

**Comment by Asadullah-Dal17** [comment]
Detection is not happening in the reference image, make sure to provide correct path, reference image.
